# Generated by Django 4.0.10 on 2023-11-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre_ideal',
            field=models.IntegerField(default=1),
        ),
    ]
