# Generated by Django 4.0.10 on 2023-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_disciplina_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda_por_disciplina',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
